from __future__ import annotations

from pathlib import Path

import pytest

from llm_wiki.config import WikiConfig
from llm_wiki.issues.queue import IssueQueue
from llm_wiki.librarian.agent import LibrarianAgent
from llm_wiki.manifest import ManifestEntry
from llm_wiki.vault import Vault


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class _StubLLM:
    """Minimal async LLM stub — should never be called in these tests."""

    async def complete(self, messages, temperature=0.7, priority="query"):
        raise AssertionError("LLM must not be called during index regeneration")


def _make_agent(vault: Vault, vault_root: Path) -> LibrarianAgent:
    return LibrarianAgent(
        vault,
        vault_root,
        _StubLLM(),
        IssueQueue(vault_root / "wiki"),
        WikiConfig(),
    )


# ---------------------------------------------------------------------------
# Unit tests for _regenerate_index() directly
# ---------------------------------------------------------------------------


def test_regenerate_index_creates_file(sample_vault: Path):
    """_regenerate_index() writes wiki/index.md to the correct path."""
    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)

    result = agent._regenerate_index()

    assert result is True
    index_path = sample_vault / "wiki" / "index.md"
    assert index_path.exists()


def test_regenerate_index_has_header(sample_vault: Path):
    """The generated file starts with the expected header."""
    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)
    agent._regenerate_index()

    content = (sample_vault / "wiki" / "index.md").read_text(encoding="utf-8")
    assert content.startswith("# Index\n")
    assert "<!-- auto-generated by librarian" in content


def test_regenerate_index_excludes_index_page(sample_vault: Path):
    """The index page itself must not appear as an entry."""
    # Create an index.md in the vault wiki dir
    index_md = sample_vault / "wiki" / "index.md"
    index_md.write_text("---\ntitle: Index\n---\n\n## Overview\n\nTable of contents.\n")

    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)
    agent._regenerate_index()

    content = (sample_vault / "wiki" / "index.md").read_text(encoding="utf-8")
    # The wikilink [[index]] must not appear in the regenerated content
    assert "[[index]]" not in content


def test_regenerate_index_clusters_sorted_alphabetically(sample_vault: Path):
    """Non-root clusters appear before root and in alphabetical order."""
    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)
    agent._regenerate_index()

    content = (sample_vault / "wiki" / "index.md").read_text(encoding="utf-8")

    # The sample vault has "bioinformatics", "machine-learning", and "root" clusters.
    bio_pos = content.find("## Bioinformatics")
    ml_pos = content.find("## Machine Learning")
    root_pos = content.find("## Root")

    assert bio_pos != -1, "Bioinformatics cluster heading missing"
    assert ml_pos != -1, "Machine Learning cluster heading missing"
    assert root_pos != -1, "Root cluster heading missing"

    # alphabetical order: bioinformatics < machine-learning, root always last
    assert bio_pos < ml_pos < root_pos


def test_regenerate_index_root_cluster_last(sample_vault: Path):
    """The 'root' cluster section always appears after all other clusters."""
    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)
    agent._regenerate_index()

    content = (sample_vault / "wiki" / "index.md").read_text(encoding="utf-8")

    # Find the position of "## Root" and every other "## " heading
    lines = content.splitlines()
    section_positions = [
        (i, line) for i, line in enumerate(lines) if line.startswith("## ")
    ]
    assert section_positions, "No cluster headings found"

    last_section = section_positions[-1][1]
    assert last_section == "## Root", (
        f"Expected last section to be '## Root', got '{last_section}'"
    )


def test_regenerate_index_pages_sorted_within_cluster(sample_vault: Path):
    """Pages within a cluster are sorted alphabetically by slug."""
    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)
    agent._regenerate_index()

    content = (sample_vault / "wiki" / "index.md").read_text(encoding="utf-8")

    # In the bioinformatics cluster: inter-rep-variant-analysis < srna-embeddings
    inter_pos = content.find("[[inter-rep-variant-analysis]]")
    srna_pos = content.find("[[srna-embeddings]]")

    assert inter_pos != -1
    assert srna_pos != -1
    assert inter_pos < srna_pos, "Pages not sorted alphabetically within cluster"


def test_regenerate_index_uses_summary_when_present(sample_vault: Path):
    """Entry line uses entry.summary when it is non-empty."""
    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)
    agent._regenerate_index()

    content = (sample_vault / "wiki" / "index.md").read_text(encoding="utf-8")

    # srna-embeddings has a non-empty summary (first sentence of page content)
    # It should appear as "- [[srna-embeddings]] — <summary>"
    assert "[[srna-embeddings]] \u2014 " in content


def test_regenerate_index_falls_back_to_title_when_summary_empty(tmp_path: Path):
    """Falls back to entry.title when entry.summary is falsy.

    We test this by patching the vault's manifest entries directly so that
    a known entry has an empty summary — bypassing the page-parser behaviour
    (which always provides at least "...").
    """
    from unittest.mock import patch
    from llm_wiki.manifest import ManifestEntry

    wiki = tmp_path / "wiki"
    wiki.mkdir()
    (wiki / "bare-page.md").write_text("---\ntitle: Bare Page\n---\n\n## Body\n\nsome text\n")

    vault = Vault.scan(tmp_path)
    agent = _make_agent(vault, tmp_path)

    # Force summary to be empty so the fallback is exercised
    fake_entries = {
        "bare-page": ManifestEntry(
            name="bare-page",
            title="Bare Page",
            summary="",  # explicitly empty → should fall back to title
            tags=[],
            cluster="root",
            tokens=10,
            sections=[],
            links_to=[],
            links_from=[],
        )
    }
    with patch.object(vault, "manifest_entries", return_value=fake_entries):
        agent._regenerate_index()

    content = (tmp_path / "wiki" / "index.md").read_text(encoding="utf-8")
    assert "[[bare-page]] \u2014 Bare Page" in content


def test_regenerate_index_empty_vault_returns_false(tmp_path: Path):
    """Returns False and does not create a file when vault has no pages."""
    (tmp_path / "wiki").mkdir()
    vault = Vault.scan(tmp_path)
    agent = _make_agent(vault, tmp_path)

    result = agent._regenerate_index()

    assert result is False
    assert not (tmp_path / "wiki" / "index.md").exists()


def test_regenerate_index_overwrites_existing_file(sample_vault: Path):
    """Calling _regenerate_index() twice overwrites the previous output."""
    index_path = sample_vault / "wiki" / "index.md"
    index_path.write_text("stale content")

    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)
    agent._regenerate_index()

    content = index_path.read_text(encoding="utf-8")
    assert content != "stale content"
    assert "# Index" in content


# ---------------------------------------------------------------------------
# Integration: run() sets index_regenerated on LibrarianResult
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_run_sets_index_regenerated(sample_vault: Path):
    """LibrarianResult.index_regenerated is True after a successful run()."""
    vault = Vault.scan(sample_vault)
    agent = _make_agent(vault, sample_vault)

    result = await agent.run()

    assert result.index_regenerated is True
    assert (sample_vault / "wiki" / "index.md").exists()


@pytest.mark.asyncio
async def test_run_empty_vault_index_regenerated_false(tmp_path: Path):
    """run() on an empty vault sets index_regenerated to False."""
    (tmp_path / "wiki").mkdir()
    vault = Vault.scan(tmp_path)
    agent = _make_agent(vault, tmp_path)

    result = await agent.run()

    assert result.index_regenerated is False
